/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.ufes.view;

import javax.swing.JButton;
import javax.swing.JCheckBox;
import javax.swing.JComboBox;
import javax.swing.JPanel;

/**
 *
 * @author heflainrmendes
 */
public class GraficoView extends javax.swing.JFrame {

    /**
     * Creates new form GraficoView
     */
    public GraficoView() {
        initComponents();
        this.setResizable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlGrafico = new javax.swing.JPanel();
        cbTitulo = new javax.swing.JCheckBox();
        cbTituloEixo = new javax.swing.JCheckBox();
        cbLegenda = new javax.swing.JCheckBox();
        cbRotulosDeDadosValor = new javax.swing.JCheckBox();
        cbRotulosDeDadosPorcentagem = new javax.swing.JCheckBox();
        cbRotulosDeDadosPorcentagemValor = new javax.swing.JCheckBox();
        cbGrade = new javax.swing.JCheckBox();
        cbCorDasBarrasPorGrupo = new javax.swing.JCheckBox();
        cbCorDasBarras = new javax.swing.JCheckBox();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        cbxGraficoPadrao = new javax.swing.JComboBox<>();
        btnFechar = new javax.swing.JButton();
        btnRestaurarPadrao = new javax.swing.JButton();
        btnDesfazer = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        javax.swing.GroupLayout pnlGraficoLayout = new javax.swing.GroupLayout(pnlGrafico);
        pnlGrafico.setLayout(pnlGraficoLayout);
        pnlGraficoLayout.setHorizontalGroup(
            pnlGraficoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        pnlGraficoLayout.setVerticalGroup(
            pnlGraficoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 410, Short.MAX_VALUE)
        );

        cbTitulo.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        cbTitulo.setText("Título");

        cbTituloEixo.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        cbTituloEixo.setText("Título dos eixos");

        cbLegenda.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        cbLegenda.setText("Legenda");

        cbRotulosDeDadosValor.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        cbRotulosDeDadosValor.setText("Rótulo de dados - Valor");

        cbRotulosDeDadosPorcentagem.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        cbRotulosDeDadosPorcentagem.setText("Rótulos de dados - %");
        cbRotulosDeDadosPorcentagem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbRotulosDeDadosPorcentagemActionPerformed(evt);
            }
        });

        cbRotulosDeDadosPorcentagemValor.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        cbRotulosDeDadosPorcentagemValor.setText("Rótulos de dados  - % Valor");

        cbGrade.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        cbGrade.setText("Grade");

        cbCorDasBarrasPorGrupo.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        cbCorDasBarrasPorGrupo.setText("Cor das barras (por grupo)");

        cbCorDasBarras.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        cbCorDasBarras.setText("Cor das barras");

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel1.setText("Elementos gráficos:");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel2.setText("Gráfico padrão:");

        btnFechar.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnFechar.setText("Fechar");

        btnRestaurarPadrao.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnRestaurarPadrao.setText("Restaurar padrão");

        btnDesfazer.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnDesfazer.setText("Desfazer");
        btnDesfazer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDesfazerActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnDesfazer, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnRestaurarPadrao)
                        .addGap(18, 18, 18)
                        .addComponent(btnFechar, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(53, 53, 53)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(cbTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(cbLegenda, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(cbGrade, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(cbTituloEixo, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(cbRotulosDeDadosPorcentagem, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(cbRotulosDeDadosValor, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(cbRotulosDeDadosPorcentagemValor, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(cbCorDasBarras, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(cbCorDasBarrasPorGrupo, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(26, 26, 26))
                            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 256, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(pnlGrafico, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addContainerGap(558, Short.MAX_VALUE)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(27, 27, 27)
                        .addComponent(cbxGraficoPadrao, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(53, 53, 53))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbxGraficoPadrao, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cbTitulo)
                        .addGap(18, 18, 18)
                        .addComponent(cbLegenda)
                        .addGap(18, 18, 18)
                        .addComponent(cbTituloEixo)
                        .addGap(18, 18, 18)
                        .addComponent(cbRotulosDeDadosPorcentagem)
                        .addGap(18, 18, 18)
                        .addComponent(cbRotulosDeDadosValor)
                        .addGap(18, 18, 18)
                        .addComponent(cbRotulosDeDadosPorcentagemValor)
                        .addGap(18, 18, 18)
                        .addComponent(cbCorDasBarras)
                        .addGap(18, 18, 18)
                        .addComponent(cbCorDasBarrasPorGrupo)
                        .addGap(18, 18, 18)
                        .addComponent(cbGrade))
                    .addComponent(pnlGrafico, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnFechar, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnRestaurarPadrao, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnDesfazer, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(23, Short.MAX_VALUE))
        );

        pnlGrafico.getAccessibleContext().setAccessibleName("");

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void cbRotulosDeDadosPorcentagemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbRotulosDeDadosPorcentagemActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbRotulosDeDadosPorcentagemActionPerformed

    private void btnDesfazerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDesfazerActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnDesfazerActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GraficoView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GraficoView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GraficoView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GraficoView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GraficoView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDesfazer;
    private javax.swing.JButton btnFechar;
    private javax.swing.JButton btnRestaurarPadrao;
    private javax.swing.JCheckBox cbCorDasBarras;
    private javax.swing.JCheckBox cbCorDasBarrasPorGrupo;
    private javax.swing.JCheckBox cbGrade;
    private javax.swing.JCheckBox cbLegenda;
    private javax.swing.JCheckBox cbRotulosDeDadosPorcentagem;
    private javax.swing.JCheckBox cbRotulosDeDadosPorcentagemValor;
    private javax.swing.JCheckBox cbRotulosDeDadosValor;
    private javax.swing.JCheckBox cbTitulo;
    private javax.swing.JCheckBox cbTituloEixo;
    private javax.swing.JComboBox<String> cbxGraficoPadrao;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel pnlGrafico;
    // End of variables declaration//GEN-END:variables

    public JCheckBox getCbLegenda() {
        return cbLegenda;
    }

    public JCheckBox getCbRotulosDeDadosPorcentagem() {
        return cbRotulosDeDadosPorcentagem;
    }

    public JCheckBox getCbRotulosDeDadosPorcentagemValor() {
        return cbRotulosDeDadosPorcentagemValor;
    }

    public JCheckBox getCbRotulosDeDadosValor() {
        return cbRotulosDeDadosValor;
    }

    public JCheckBox getCbTitulo() {
        return cbTitulo;
    }

    public JCheckBox getCbCorDasBarras() {
        return cbCorDasBarras;
    }

    public JCheckBox getCbCorDasBarrasPorGrupo() {
        return cbCorDasBarrasPorGrupo;
    }

    public JCheckBox getCbGrade() {
        return cbGrade;
    }

    public JCheckBox getCbTituloEixo() {
        return cbTituloEixo;
    }

    public JComboBox<String> getCbxGraficoPadrao() {
        return cbxGraficoPadrao;
    }

    public JPanel getPnlGrafico() {
        return pnlGrafico;
    }

    public JButton getBtnDesfazer() {
        return btnDesfazer;
    }

    public JButton getBtnFechar() {
        return btnFechar;
    }

    public JButton getBtnRestaurarPadrao() {
        return btnRestaurarPadrao;
    }
    
    
}
